#!/bin/bash

case "$1" in
    "help")
        echo "$(basename $0) status"
        exit 0
        ;;
    *)
        STATUS=$(relx_nodetool rpc "erlang:whereis(ascensor_sup)")
        if [ "$STATUS" == "undefined" ]; then
            echo "down!"
        else
            echo "up!"
        fi
        ;;
esac
